# Generated by Django 5.1.6 on 2025-03-02 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='factored_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Wenn leer, wird die gerundete Dauer verwendet.', max_digits=10, null=True, verbose_name='Fakturierte Stunden'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
